PkFokam-Alumni-Network/CommunityWebsite

package.json

Installed material Design UI
Installed material Design UI

#1 installed material design UI library

---

src/App.js
src/components/AlumniDetails.jsx

This pull request adds the Alumni Details page component using Material-UI. 
It includes:
- A new `AlumniDetails.jsx` file in the `src/components/` folder.
- Integration of the component into the `App.js`.

Added AlumniDetails component and integrated it into App

---

package.json
src/App.js
src/components/LoginForm.jsx
src/index.css
tailwind.config.js

- Ticket details: https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/6
- Created login page based on design. Added neccessary libraries for animation.
N/A

#6 completed login form and added neccessary libraries

---

package.json
src/components/Banner.jsx
src/components/Events.jsx
src/components/Footer.jsx
src/components/Header.jsx
src/components/MainLayout.jsx
src/index.css
src/pages/Home.jsx
src/theme/theme.js
src/utils/colors.js
styles.css

Closes #4 
Added the home page

Created Landing Page

---

src/App.jsx
src/components/AlumniDetails.jsx
src/components/Header.jsx
src/components/MainLayout.jsx

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/5
Refactored Alumni Details page and added background color to our main layout.

#5 added main layout background color

---

Dockerfile

Add initial docker file

---

public/index.html

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/35
changed title of app

#35 changed title of app

---

src/App.jsx

Remove alumni details link

---

docker-compose.yml

Add docker-compose.yml for frontend, backend, and database

---

src/components/Header.jsx

Ticket details: https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/32
First iteration for nav bar refactoring

#32 refactored nav bar

---

src/components/AuthLayout.jsx
src/components/MainLayout.jsx
src/components/Onboarding.jsx
src/pages/Home.jsx

fixed unused-variables-issues

---

src/App.jsx
src/components/SplashScreen.jsx

Give warmth to the app
- Created a welcoming animation

Add a welcoming animation on login

---

src/api/axiosInstance.js
src/config.js
src/features/authSlice.jsx

This change is required to clean up the codebase by removing unnecessary console.log statements that were used for debugging purposes. These logs are no longer needed in production and can clutter the console, making it harder to identify actual issues during development.
Removed all unnecessary console.log statements across the codebase.
Ensured that the functionality of the application remains unchanged after the removal of these logs.
-  Manual Testing:
Verified that the application runs without errors after removing the console.log statements.
Checked that all features (e.g., login, dashboard, alumni details) work as expected.
- Automated Testing:
Ran existing unit tests to ensure no functionality was broken.
All tests passed successfully.

Removed all unnecessary console.log statements

---

src/App.jsx
src/components/AnnouncementCard.jsx
src/pages/AlumniDirectory.jsx
src/pages/Announcements.jsx
src/pages/UserDashboard.jsx

- Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/68
- Map icons to routes from drawer
- Made a new announcements page
- Made an announcement component
I also hid the searchBar because it was kind of gross.
After you click on "Read more"
Responsive

Add announcements page

---

src/App.jsx
src/components/EventCard.jsx
src/components/EventDetails.jsx
src/pages/Events.jsx
src/pages/UserDashboard.jsx

- Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/7
- Made a new page for events

Add events

---

src/components/LoginForm.jsx
src/utils/error.js

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/76
Added email & password validation.

#76  Add email and password validation on login form #76

---

src/components/ContactUsForm.jsx
src/pages/ContactUsPage.jsx
src/pages/Home.jsx

- Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/70
added contact us form & page

Create a contact us form #70

---

src/App.jsx
src/api/authService.js
src/components/LoginForm.jsx
src/components/SplashScreen.jsx
src/features/authSlice.jsx

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/57
Added logged in username to splash screen

Pass the first name of the authenticated user to the splash screen #57

---

src/pages/HomePage.jsx
src/pages/UserDashboard.jsx

Add homepage widget

---

src/components/AlumiEditProfile.jsx
src/components/AlumniProfile.jsx
src/components/EventCard.jsx
src/pages/AlumniDirectory.jsx
src/pages/Events.jsx
src/pages/HomePage.jsx

Small changes

---

src/App.jsx
src/components/Header.jsx
src/pages/Onboarding.jsx
src/pages/UserDashboard.jsx

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/86
Moved onboarding page to resources page after login

Move student onboarding page to resources page after login #86

---

src/components/Header.jsx

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/88
Removed about us from header temporarily

Remove About us in header temporarily #88

---

src/App.jsx

fixed user name missing when splash screen refreshed

fix user name missing when splash screen refreshed

---

src/api/alumniUsersService.js
src/features/alumniUsersSlice.js
src/pages/AlumniDirectory.jsx
src/store/store.js

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/92
integrated get all users api

Integrate the 'Get all users' API #92

---

src/api/announcementsService.js
src/features/alumniUsersSlice.js
src/features/announcementsSlice.js
src/pages/Announcements.jsx
src/store/store.js

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/93
integrated get all announcements api

Integrate the 'Get all announcements' API #93

---

src/App.jsx
src/api/userService.js
src/components/AlumniProfile.jsx
src/features/alumniUsersSlice.js
src/helpers/coreHelper.js

Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/95
integrated get user mentees api

Integrate the 'Get mentee' API #95

---

src/components/AlumiEditProfile.jsx
src/components/AlumniCard.jsx
src/components/AlumniDetailsCard.jsx
src/components/AlumniProfile.jsx
src/constants/alumnidata.js
src/pages/AlumniDirectory.jsx

To make the frontend match the response of the backend
- Removed fields that made it too much look like linkedin
- Make the response match

Make the frontend match with the backend

---

src/components/LoginForm.jsx
src/features/authSlice.jsx

Avoiding calling getUser API after login to get logged in user details. User details returned directly by login V2
integrate login api v2

Loic/integrate login api v2 

---

src/components/AlumiEditProfile.jsx
src/components/AlumniCard.jsx

- Now when you make the change to the edit fields, when you click saved, the changes persist

Modify the edit fields

---

src/pages/AlumniDirectory.jsx

Integrate actual users

---

src/components/AlumiEditProfile.jsx
src/components/AlumniDetailsCard.jsx
src/components/AlumniProfile.jsx
src/components/SplashScreen.jsx
src/features/alumniSlice.js
src/features/authType.js

Integrate update user api in reducer

---

src/api/userService.js
src/components/AlumiEditProfile.jsx
src/features/alumniSlice.js

- Closes https://github.com/PkFokam-Alumni-Network/CommunityWebsite/issues/96
- Added the endpoint for PUT update profile picture
- Added some reducers

Add support for updating profile picture
